name: Daily Cat Bot

on:
  schedule:
    - cron: '0 5 * * *'  # Runs daily at 9 AM UTC (adjust as needed)
  workflow_dispatch:      # Allows manual triggering

jobs:
  send-cat-picture:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Execute Daily Cat Bot
      env:
        TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
        BASE_URL: ${{ secrets.BASE_URL }}
      run: |
        python bot.py
